apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-argocd
  namespace: argocd
spec: 
  source:
    repoURL: https://github.com/Aditi336/ci_cd_pipeline_kub.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
